added new write-data logic & updated permission check/loadsave to use it

diff --git a/factorio b/factorio
--- a/factorio
+++ b/factorio
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+debug(){
+  if [ ${DEBUG} -gt 0 ]; then
+    echo "DEBUG: $@" >&2
+  fi
+}
+
 # Load config file
 if [ -L $0 ]; then
   source `readlink -e $0 | sed "s:[^/]*$:config:"`
@@ -24,10 +30,6 @@ if [ -z "${HEADLESS}" ]; then
   # This is a server init script, assume headless default
   HEADLESS=1
 fi
-if [ -z "${PIDFILE}" ]; then
-  PIDFILE="${FACTORIO_PATH}/${SERVICE_NAME}.pid"
-fi
-
 if [ -z "${FCONF}" ]; then
   echo "FCONF config missing! Add it to your config file"
   exit 1
@@ -38,12 +40,14 @@ if ! [ -e ${FCONF} ]; then
   echo "by running: sudo -u $USERNAME ${BINARY} --start-server ${SAVE_NAME}"
   exit 1
 fi
-
-debug(){
-  if [ ${DEBUG} -gt 0 ]; then
-    echo "DEBUG LOG: $@" >&2
-  fi
-}
+if [ -z "${WRITE_DIR}" ]; then
+  # figure out the write-data path (where factorio looks for saves and mods)
+  # Note - this is a hefty little operation, possible cause of head ache down the road
+  # as it relies on the factorio write dir to live ../../ up from the binary if __PATH__executable__
+  # is used in the config file.. for now, that's the default so cross your fingers it will not change ;)
+  WRITE_DIR=$(dirname "$(echo `grep "^write-data=" "$FCONF"` |cut -d'=' -f2 |sed -e 's#__PATH__executable__#'$(dirname "$BINARY")/..'#g')")
+fi
+debug "write path: $WRITE_DIR"
 
 usage(){
   echo "Usage: $0 COMMAND"
@@ -70,7 +74,7 @@ as_user() {
 }
 
 refresh_save(){
-  savedir="${FACTORIO_PATH}/saves"
+  savedir="${WRITE_DIR}/saves"
 
   # Check to see if save dir actually exists
   if ! [ -e ${savedir} ]; then
@@ -137,7 +141,7 @@ start_service() {
   fi
 
   if ! check_permissions; then
-    echo "Error! Incorrect permissions"
+    echo "Error! Incorrect permissions, unable to write to dir \"$WRITE_DIR\""
     return 1
   fi
 
@@ -200,13 +204,10 @@ stop_service() {
 }
 
 check_permissions() {
-  as_user "touch $PIDFILE"
-  if ! as_user "test -w '$PIDFILE'" ; then
-    echo "Check Permissions. Cannot write to $PIDFILE. Correct the permissions and then excute: $0 status"
+  if ! as_user "test -w '$WRITE_DIR'" ; then
+    debug "Check Permissions. Cannot write to $WRITE_DIR"
     return 1
   fi
-
-  return 0
 }
 
 test_deps(){
@@ -445,7 +446,7 @@ case "$1" in
 
   load-save)
     # Ensure we get a new save file name
-    newsave=${FACTORIO_PATH}/saves/$2.zip
+    newsave=${WRITE_DIR}/saves/$2.zip
     if [ ! -f "${newsave}" ]; then
       echo "Save \"${newsave}\" does not exist, aborting action!"
       exit 1
