allow some commands to run without configuring server-settings.json

diff --git a/factorio b/factorio
--- a/factorio
+++ b/factorio
@@ -50,64 +50,66 @@ if [ -z ${BINARY} ]; then
   BINARY="${FACTORIO_PATH}/bin/x64/factorio"
 fi
 
-
-if ! [ "$1" == "install" ]; then
-  if ! [ -e ${BINARY} ]; then
-    echo "Could not find factorio binary! ${BINARY}"
-    echo "(if you store your binary some place else, override BINARY='/your/path' in the config)"
-    exit 1
-  fi
-
-  if [ -z ${FCONF} ]; then
-    FCONF="${FACTORIO_PATH}/config/config.ini"
-  fi
-
-  if ! [ -e "${SERVER_SETTINGS}" ]; then
-    echo "Could not find factorio server settings file: ${SERVER_SETTINGS}"
-    echo "Update your config and point SERVER_SETTINGS to a modified version of data/server-settings.example.json"
-    exit 1
-  fi
-
-  if ! [ -e ${FCONF} ]; then
-    echo "Could not find factorio config file: ${FCONF}"
-    echo "If this is the first time you run this script you need to generate the config.ini by starting the server manually."
-    echo "(also make sure you have a save to run or the server will not start)"
-    echo
-    echo "Create save: sudo -u ${USERNAME} ${BINARY} --create ${FACTORIO_PATH}/saves/my_savegame"
-    echo "Start server: sudo -u ${USERNAME} ${BINARY} --start-server-load-latest"
-    echo
-    echo "(If you rather store the config.ini in another location, set FCONF='/your/path' in this scripts config file)"
-    exit 1
-  fi
-  if [ -z "${WRITE_DIR}" ]; then
-    # figure out the write-data path (where factorio looks for saves and mods)
-    # Note - this is a hefty little operation, possible cause of head ache down the road
-    # as it relies on the factorio write dir to live ../../ up from the binary if __PATH__executable__
-    # is used in the config file.. for now, that's the default so cross your fingers it will not change ;)
-    debug "Determining WRITE_DIR based on ${FCONF}, IF you edited write-data from the default, this probably fails"
-    WRITE_DIR=$(dirname "$(echo `grep "^write-data=" "$FCONF"` |cut -d'=' -f2 |sed -e 's#__PATH__executable__#'$(dirname "$BINARY")/..'#g')")
-  fi
-  debug "write path: $WRITE_DIR"
-
-  PIDFILE="${WRITE_DIR}/server.pid"
-
-  if [ -z "${FIFO}" ];then
-    FIFO="${WRITE_DIR}/server.fifo"
-  fi
-
-  if [ -z "${CMDOUT}" ];then
-    CMDOUT="${WRITE_DIR}/server.out"
-  fi
-
-  if [ -z "${SAVELOG}" ]; then
-    SAVELOG=0
-  fi
-
-  # Finally, set up the invocation
-  INVOCATION="${BINARY} --config ${FCONF} --port ${PORT} --start-server-load-latest --server-settings ${SERVER_SETTINGS} ${RCON} ${EXTRA_BINARGS}"
-
-fi
-
+case "$1" in
+  install|help|listcommands|version|"")
+    ;;
+  *)
+    if ! [ -e ${BINARY} ]; then
+      echo "Could not find factorio binary! ${BINARY}"
+      echo "(if you store your binary some place else, override BINARY='/your/path' in the config)"
+      exit 1
+    fi
+  
+    if [ -z ${FCONF} ]; then
+      FCONF="${FACTORIO_PATH}/config/config.ini"
+    fi
+  
+    if ! [ -e "${SERVER_SETTINGS}" ]; then
+      echo "Could not find factorio server settings file: ${SERVER_SETTINGS}"
+      echo "Update your config and point SERVER_SETTINGS to a modified version of data/server-settings.example.json"
+      exit 1
+    fi
+  
+    if ! [ -e ${FCONF} ]; then
+      echo "Could not find factorio config file: ${FCONF}"
+      echo "If this is the first time you run this script you need to generate the config.ini by starting the server manually."
+      echo "(also make sure you have a save to run or the server will not start)"
+      echo
+      echo "Create save: sudo -u ${USERNAME} ${BINARY} --create ${FACTORIO_PATH}/saves/my_savegame"
+      echo "Start server: sudo -u ${USERNAME} ${BINARY} --start-server-load-latest"
+      echo
+      echo "(If you rather store the config.ini in another location, set FCONF='/your/path' in this scripts config file)"
+      exit 1
+    fi
+    if [ -z "${WRITE_DIR}" ]; then
+      # figure out the write-data path (where factorio looks for saves and mods)
+      # Note - this is a hefty little operation, possible cause of head ache down the road
+      # as it relies on the factorio write dir to live ../../ up from the binary if __PATH__executable__
+      # is used in the config file.. for now, that's the default so cross your fingers it will not change ;)
+      debug "Determining WRITE_DIR based on ${FCONF}, IF you edited write-data from the default, this probably fails"
+      WRITE_DIR=$(dirname "$(echo `grep "^write-data=" "$FCONF"` |cut -d'=' -f2 |sed -e 's#__PATH__executable__#'$(dirname "$BINARY")/..'#g')")
+    fi
+    debug "write path: $WRITE_DIR"
+  
+    PIDFILE="${WRITE_DIR}/server.pid"
+  
+    if [ -z "${FIFO}" ];then
+      FIFO="${WRITE_DIR}/server.fifo"
+    fi
+  
+    if [ -z "${CMDOUT}" ];then
+      CMDOUT="${WRITE_DIR}/server.out"
+    fi
+  
+    if [ -z "${SAVELOG}" ]; then
+      SAVELOG=0
+    fi
+  
+    # Finally, set up the invocation
+    INVOCATION="${BINARY} --config ${FCONF} --port ${PORT} --start-server-load-latest --server-settings ${SERVER_SETTINGS} ${RCON} ${EXTRA_BINARGS}"
+    ;;
+esac
+  
 usage(){
   echo "Usage: $0 COMMAND"
   echo
