fixes #45, informs user of missing config

diff --git a/factorio b/factorio
--- a/factorio
+++ b/factorio
@@ -32,6 +32,12 @@ if [ -z "${FCONF}" ]; then
   echo "FCONF config missing! Add it to your config file"
   exit 1
 fi
+if ! [ -e ${FCONF} ]; then
+  echo "Could not find factorio config file: ${FCONF}"
+  echo "If this is the first time you run this script; You might need to generate the config.ini"
+  echo "by running: sudo -u $USERNAME ${BINARY} --start-server ${SAVE_NAME}"
+  exit 1
+fi
 
 debug(){
   if [ ${DEBUG} -gt 0 ]; then
