download latest headless & generate default config.ini

diff --git a/factorio b/factorio
--- a/factorio
+++ b/factorio
@@ -39,19 +39,19 @@ if [ -z "${HEADLESS}" ]; then
   # This is a server init script, assume headless default
   HEADLESS=1
 fi
-
+if [ -z "${LATEST_HEADLESS_URL}" ]; then
+  LATEST_HEADLESS_URL="https://www.factorio.com/get-download/latest/headless/linux64"
+fi
 if [ -z "${NONCMDPATTERN}" ]; then
-  # This is a server init script, assume headless default
   NONCMDPATTERN='(^\s*(\s*[0-9]+\.[0-9]+|\)|\())|(Players:$)'
+fi
+if [ -z ${BINARY} ]; then
+  # Factorio headless only comes in x64 flavour - if you run anything else, override it in the config
+  BINARY="${FACTORIO_PATH}/bin/x64/factorio"
 fi
 
 
 if ! [ "$1" == "install" ]; then
-  if [ -z ${BINARY} ]; then
-    # Factorio headless only comes in x64 flavour - if you run anything else, override it in the config
-    BINARY="${FACTORIO_PATH}/bin/x64/factorio"
-  fi
-
   if ! [ -e ${BINARY} ]; then
     echo "Could not find factorio binary! ${BINARY}"
     echo "(if you store your binary some place else, override BINARY='/your/path' in the config)"
@@ -123,7 +123,7 @@ usage(){
   echo -e "   new-game name [map-gen-settings] \t Stops the server and creates a new game with the specified name using the specified map gen settings json file"
   echo -e "   save-game name \t\t\t Stops the server and saves game to specified save"
   echo -e "   load-save name \t\t\t Stops the server and loads the specified save"
-  echo -e "   install tarball \t\t\t Installs the server with specified tarball"
+  echo -e "   install [tarball] \t\t\t Installs the server with optional specified tarball (omit to download and use the latest headless server from Wube)"
   echo -e "   update [--dry-run] \t\t\t Updates the server"
   echo -e "   invocation \t\t\t\t Outputs the invocation for debugging purpose"
   echo -e "   listcommands \t\t\t List all init-commands"
@@ -323,16 +323,20 @@ install(){
     exit 1
   fi
 
-  # Prevent accitential overwrites
+  # Prevent accidential overwrites
   if [ -e "${expected_path}" ]; then
     echo "Aborting install, ${FACTORIO_PATH} already exists"
     exit 1
   fi
 
   tarball=$1
-  if ! [ -f "${tarball}" ]; then
-    echo "Install package does not exist! ${tarball}"
-    exit 1
+  if ! [ -z "$tarball" ]; then
+    if ! [ -f "${tarball}" ]; then
+      echo "Install package does not exist! ${tarball}"
+      exit 1
+    fi
+  else
+    downloadlatest=1
   fi
 
   target="`dirname ${FACTORIO_PATH}`"
@@ -342,10 +346,17 @@ install(){
     exit 1
   fi
 
-  echo "Installing ${tarball} ..."
-  if ! tar -xzvf "${tarball}" --directory "${target}"; then
-    echo "Install failed!"
-    exit 1
+  if [ $downloadlatest ]; then
+    if ! wget ${LATEST_HEADLESS_URL} -O - | tar -xzv --directory "${target}"; then
+      echo "Install failed!"
+      exit 1
+    fi
+  else
+    echo "Installing ${tarball} ..."
+    if ! tar -xzvf "${tarball}" --directory "${target}"; then
+      echo "Install failed!"
+      exit 1
+    fi
   fi
 
   echo "Applying file ownership ..."
@@ -354,7 +365,15 @@ install(){
     exit 1
   fi
 
-  echo "Installation complete, edit the config and start your server"
+  # Generate default config.ini by creating a save
+  as_user "${BINARY} --create ${FACTORIO_PATH}/saves/server-save"
+  if [ $? -eq 0 ]; then
+    echo "Installation complete, edit data/server-settings.json and start your server"
+    exit 0
+  else
+    echo "Failed to create save, review the output above to recover"
+    exit 1
+  fi
 }
 
 get_bin_version(){
