another take on systemd

diff --git a/factorio b/factorio
--- a/factorio
+++ b/factorio
@@ -85,6 +85,8 @@ usage(){
   echo -e "   update [--dry-run] \t Updates the server"
 }
 
+
+
 ME=`whoami`
 as_user() {
   if [ $ME == $USERNAME ]; then
@@ -107,6 +109,19 @@ find_pid(){
   else
     echo ${pid}
   fi
+}
+
+# Generate a usable EnvironmentFile based on our config for use with systemd for those so inclined
+gen_systemd_env(){
+  envfile="$1"
+  if ! touch "$envfile"; then
+    echo "Failed to touch envfile: $envfile"
+    echo "(ensure you have proper permissions to do this)"
+    exit 1
+  fi
+  
+  echo "#EnvironmentFile generated by factorio-init" > $envfile
+  echo "INVOCATION=${INVOCATION}" >> $envfile
 }
 
 is_running() {
@@ -501,6 +516,9 @@ case "$1" in
           ;;
       esac
     fi
+    ;;
+  gen-systemdenv)
+    gen_systemd_env "$2"
     ;;
   install)
     install "$2"
