more default options, build invocation within the script instead

diff --git a/factorio b/factorio
--- a/factorio
+++ b/factorio
@@ -41,9 +41,19 @@ if [ -z "${HEADLESS}" ]; then
 fi
 
 if ! [ $1 == "install" ]; then
-  if [ -z ${FCONF} ]; then
-    echo "Missing FCONF, ensure it's defined in your config and try again"
+  if [ -z ${BINARY} ]; then
+    # Factorio headless only comes in x64 flavour - if you run anything else, override it in the config
+    BINARY="${FACTORIO_PATH}/bin/x64/factorio"
+  fi
+
+  if ! [ -e ${BINARY} ]; then
+    echo "Could not find factorio binary! ${BINARY}"
+    echo "(if you store your binary some place else, override BINARY='/your/path' in the config)"
     exit 1
+  fi
+
+  if [ -z ${FCONF} ]; then
+    FCONF="${FACTORIO_PATH}/config/config.ini"
   fi
   
   if ! [ -e "${SERVER_SETTINGS}" ]; then
@@ -54,9 +64,13 @@ if ! [ $1 == "install" ]; then
 
   if ! [ -e ${FCONF} ]; then
     echo "Could not find factorio config file: ${FCONF}"
-    echo "If this is the first time you run this script; You might need to generate the config.ini"
-    echo "(also make sure the save exist or the command will fail)"
-    echo "by running: sudo -u $USERNAME ${BINARY} --start-server ${SAVE_NAME}"
+    echo "If this is the first time you run this script you need to generate the config.ini by starting the server manually."
+    echo "(also make sure you have a save to run or the server will not start)"
+    echo
+    echo "Create save: sudo -u ${USERNAME} ${BINARY} --create ${FACTORIO_PATH}/saves/my_savegame"
+    echo "Start server: sudo -u ${USERNAME} ${BINARY} --start-server-load-latest"
+    echo
+    echo "(If you rather store the config.ini in another location, set FCONF='/your/path' in this scripts config file)"
     exit 1
   fi
   if [ -z "${WRITE_DIR}" ]; then
@@ -64,6 +78,7 @@ if ! [ $1 == "install" ]; then
     # Note - this is a hefty little operation, possible cause of head ache down the road
     # as it relies on the factorio write dir to live ../../ up from the binary if __PATH__executable__
     # is used in the config file.. for now, that's the default so cross your fingers it will not change ;)
+    debug "Determining WRITE_DIR based on ${FCONF}, IF you edited write-data from the default, this probably fails"
     WRITE_DIR=$(dirname "$(echo `grep "^write-data=" "$FCONF"` |cut -d'=' -f2 |sed -e 's#__PATH__executable__#'$(dirname "$BINARY")/..'#g')")
   fi
   debug "write path: $WRITE_DIR"
@@ -73,6 +88,9 @@ if ! [ $1 == "install" ]; then
   if [ -z "${FIFO}" ];then
     FIFO="${WRITE_DIR}/server.fifo"
   fi
+
+  # Finally, set up the invocation
+  INVOCATION="${BINARY} --config ${FCONF} --port ${PORT} --start-server-load-latest --server-settings ${SERVER_SETTINGS} --autosave-interval ${AUTOSAVE_INTERVAL} --autosave-slots ${AUTOSAVE_SLOTS} --latency-ms ${LATENCY} ${RCON} ${EXTRA_BINARGS}"
 
 fi
 
@@ -90,6 +108,7 @@ usage(){
   echo -e "   load-save name \t Stops the server and loads the specified save"
   echo -e "   install tarball \t Installs the server with specified tarball"
   echo -e "   update [--dry-run] \t Updates the server"
+  echo -e "   invocation \t\t Outputs the invocation for debugging purpose"
 }
 
 ME=`whoami`
@@ -519,6 +538,9 @@ case "$1" in
     ;;
   update)
     update "$2"
+    ;;
+  inv|invocation)
+    echo ${INVOCATION}
     ;;
   help|--help|-h)
     usage
